---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fanx.
--- DateTime: 2022/1/21 20:23
---
-- 将key传递到变量methodKey
local methodKey = KEYS[1]
-- 将value传递到变量limit
local limit = tonumber(ARGV[1])
-- 调用lua redis对象的get(methodKey)命令查询对应的访问次数,如果没有获取到则返回0
local count = tonumber(redis.call('get', methodKey) or '0')
-- 是否超出当前阈值
if count + 1 > limit then
    return false;
else
    -- 没有超过阈值
    -- 设置当前访问的数量 + 1
    redis.call('INCRBY', methodKey, 1)
    -- 设置过期时间
    redis.call('EXPIRE', methodKey, 1)
    return true
end